### PR TITLE
Structure

### PR DESCRIPTION
**Pull request by gidden**
Hi everyone,

I'm hoping to use this PR as an initial conversation point. I do not mean it to be a final proposal at all, only a suggestion. This is my attempt at moving sections/tables and adding some arguments.

I am finding the implementation section to just be too much to slog through, even as a co author. I think that this level of detail fits very well into an annex/appendix/supplementary material. I have moved it there for now (part and parcel -- though I definitely think we can bring some back.. again a starting point).

Further, I am finding the high detailed discussion in some of the methodology could be moved as well. I have proposed such a move.

Finally, I think the most propelling case we want to make here is in lines saved (perhaps someone could suggest some other compelling metrics). I wrote short script [here](https://gist.github.com/gidden/e0d4da8bd27dca43f040) which produces a table of lines saved for each Cycamore archetype. I really think we need to be compelling with the paper -- why are we writing it in the first place? Why is it saving us time/effort/efficiency? We offer some anecdotal points, but we can offer numbers too.

Looking forward to the discussion.

Cheers,
Matt

### CODE REVIEW

**Comment by scopatz** [comment]
First off, thanks a ton for putting this in @gidden! I totally dig the line-saved table.  Is there any reason to not pull this in right now? 

We could probably continue to have more discussion in another issue....

**Comment by scopatz** [comment]
I'll of course hold off on merging if you want

**Comment by katyhuff** [comment]
+10

**Comment by gidden** [comment]
Nope, if you like all of it, feel free to pull!

**Comment by gidden** [comment]
Ok, updated the table to 1.3.1 and made the rows nicer, should be good to go.

**Pull request merged**
