### PR TITLE
Minor

### PR DESCRIPTION
**Pull request by katyhuff**
Extremely minor changes. There shouldn't be any major concerns about the changes I've made here (though please don't hesitate to express them if there are). I have a more complex set of changes coming in a separate PR.

### CODE REVIEW

**Comment by scopatz** [comment]
Thanks @katyhuff!

**Comment by katyhuff** [comment]
Thanks @scopatz .  I never got around to pushing the more complex changes. I'll try again tomorrow night, unless that's too late... in which case.. oh well.

**Comment by scopatz** [comment]
No such thing as too late for this one.

**Comment by scopatz** [comment]
Thanks again!

**Pull request merged**
